---
title: "sim-tools"
author:
  - name: Tom Monks
    affiliation: University of Exeter
    orcid: 0000-0003-2631-4481
  - name: Amy Heather
    affiliation: University of Exeter
    orcid: 0000-0002-6596-3479
  - name: Alison Harper
    affiliation: University of Exeter
    orcid: 0000-0001-5274-5037
---

We have developed a Python package to support discrete-event simulation (DES) and monte-carlo simulation education and applied simulation research. Features:

1. Implementation of classic Optimisation via Simulation procedures such as KN, KN++, OBCA and OBCA-m

2. Theoretical and empirical distributions module that includes classes that encapsulate a random number stream, seed, and distribution parameters.

3. An extendable Distribution registry that provides a quick reproduible way to parameterise simulation models.

4. Implementation of Thinning to sample from Non-stationary Poisson Processes (time-dependent) in a DES.

5. Automatic selection of the number of replications to run via the Replications Algorithm.

6. EXPERIMENTAL: model trace functionality to support debugging of simulation models.

You can find the package on [GitHub](https://github.com/TomMonks/sim-tools), [PyPI](https://pypi.org/pypi/sim-tools/), and [Conda](https://anaconda.org/conda-forge/sim-tools)

## Package documentation

The `sim-tools` documentation is available at <https://tommonks.github.io/sim-tools/>.

```{=html}
<div class="iframe-wrapper">
  <div class="iframe-header">
    <span>Website preview:</span>
    <a href="https://tommonks.github.io/sim-tools/"
       target="_blank" rel="noopener">
      View full website in new tab
    </a>
  </div>

  <iframe
    width="100%"
    height="500"
    src="https://tommonks.github.io/sim-tools/"
    title="sim-tools documentation">
  </iframe>
</div>
<br>
```

<br>
---

*This page was written by Amy Heather and reflects her interpretation of this work, which may not fully represent the views of all project authors or affiliated institutions.*